# Generated by Django 4.1.4 on 2023-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50, unique=True)),
                ('categoryicon', models.CharField(max_length=100)),
            ],
        ),
    ]
