# Generated by Django 4.1.4 on 2023-02-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Category',
        ),
    ]
