# Generated by Django 4.1.4 on 2023-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_register_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.CharField(max_length=50, unique=True)),
                ('categoryname', models.CharField(max_length=50)),
                ('subcategoryicon', models.CharField(max_length=100)),
            ],
        ),
    ]
