# Generated by Django 4.1.4 on 2023-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('atitle', models.CharField(max_length=50)),
                ('acategory', models.CharField(max_length=50)),
                ('adescription', models.CharField(max_length=100)),
                ('baseprice', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
